### PR TITLE
Github workflow configuration for automated pagespeed results

### PR DESCRIPTION
**Pull request by Macleykun**
I found your repo and didn't wanted to keep sending requests to your server, everytime someone would load the readme.
I didn't wanted to check every now and then and update the svg files, so i automated it with github workflows.

Currently this pull request is:
# Not suiteable to be merged yet!

I want to discuss if your happy with how i called certain envs and how i layed the jobs/steps out.

Every user can use this, and only would need to add their preferd website.

Optionally users can add multiple curl's to get multiple reports with various changes.

There's one bug which only happens if you re-run the job. B/c it re-runs, it will not use the most recent commit and therefore exit 1 b/c it's behind. I tried to fix this but haven't found anything yet. However it's a small thing and i advice people to just start another job.

Pretty sure that if there's no changes, everything will just exit safely.

I would love to hear your feedback on this!

### CODE REVIEW

**Comment by ankurparihar** [comment]
Hi @Macleykun 
Thanks for this update :)

This is my first time working on github actions! I have read the action yml file, it looks fine and I have only few suggestions.

Please remove the last commit, that was committed by github-actions! (disable this action as we're not using it for this repo)
And also move the pagespeed url to env variable.
Lastly, use curly braces while using them as `${WEBSITE}` instead of `$WEBSITE`, because [stackoverflow question](https://stackoverflow.com/questions/8748831/when-do-we-need-curly-braces-around-shell-variables)

And then we're good to merge :)

**Comment by Macleykun** [comment]
How’s this so far?
wasn’t sure what meant with: “move the pagespeed url to env variable”
I though I used (local) env variables already.

**Comment by ankurparihar** [comment]
Hey, sorry for late reply, I'm busy elsewhere so I'm getting less time here.

**Comment by ankurparihar** [comment]
This looks wonderful!

There were few errors in referencing env variables, which I have updated in a gist.
Also there was an bot email address, that I am not much aware of. So I have put a default action email instead.

You can find the updated file in this gist: https://gist.github.com/ankurparihar/b943f97c93f3d0fe7768e392d7401f84

**Comment by ankurparihar** [comment]
As for the gtmetrix, yes, they are moving to lighthouse ([blog](https://gtmetrix.com/blog/welcome-to-the-new-gtmetrix-powered-by-lighthouse/)) and the current pagespeed API we're using already provides lighthouse data. They do have [REST API](https://gtmetrix.com/api/) but there might be some changes because its under development.

So for now, we'll stick to Google's pagespeed. In future, if gtmetrix proves to be better and useful than pagespeed, I'll consider using that.

Thanks for the suggestion.

**Comment by Macleykun** [comment]
So i looked at the gist but noticed a few things like the cron and the dispatch and some old naming like website.
I kept those changes as those are needed to make this thing automated/easier to update. People can uncomment the cron job if they like to use it.
Updating whenever smth is pushed/pulled is also a good idea maybe, but i'm afraid that for people who do this multiple times a day might be a bit to much for the api. However if you wish for me to also add on push and pull i certainly will do that :).
Thanks for that simpeler mail for github actions, i didn't liked that long weird adres myself either.
Also i made the whole naming a bit more consistent.

Thanks for considering gtmetrix :) hopefully one day they also include pagespeed somehow so that gtmetrix becomes one fully fledged performance grading tool!

If ya want any specific changes, just let me know

**Comment by ankurparihar** [comment]
Good point, yes, we should leave it to user how they want to run actions.

Okay, looks good!

**Comment by ankurparihar** [comment]
Closes https://github.com/ankurparihar/readme-pagespeed-insights/issues/2

**Pull request merged**
